// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routers

import (
	"github.com/nmcalinden/footpal/config"
	"github.com/nmcalinden/footpal/controllers"
	"github.com/nmcalinden/footpal/repository"
	"github.com/nmcalinden/footpal/services"
)

// Injectors from wire.go:

func InitializeBookingController() *controllers.BookingController {
	db := config.GetConnection()
	bookingRepository := repository.NewBookingRepository(db)
	bookingService := services.NewBookingService(bookingRepository)
	bookingController := controllers.NewBookingController(bookingService)
	return bookingController
}

func InitializeMatchController() *controllers.MatchController {
	db := config.GetConnection()
	matchRepository := repository.NewMatchRepository(db)
	matchPlayerRepository := repository.NewMatchPlayerRepository(db)
	matchService := services.NewMatchService(matchRepository, matchPlayerRepository)
	matchController := controllers.NewMatchController(matchService)
	return matchController
}

func InitializePlayerController() *controllers.PlayerController {
	db := config.GetConnection()
	playerRepository := repository.NewPlayerRepository(db)
	userRepository := repository.NewUserRepository(db)
	matchRepository := repository.NewMatchRepository(db)
	matchPlayerRepository := repository.NewMatchPlayerRepository(db)
	squadRepository := repository.NewSquadRepository(db)
	playerService := services.NewPlayerService(playerRepository, userRepository, matchRepository, matchPlayerRepository, squadRepository)
	playerController := controllers.NewPlayerController(playerService)
	return playerController
}

func InitializeSquadController() *controllers.SquadController {
	db := config.GetConnection()
	playerRepository := repository.NewPlayerRepository(db)
	squadRepository := repository.NewSquadRepository(db)
	squadService := services.NewSquadService(playerRepository, squadRepository)
	squadController := controllers.NewSquadController(squadService)
	return squadController
}

func InitializeUserController() *controllers.UserController {
	db := config.GetConnection()
	userRepository := repository.NewUserRepository(db)
	playerRepository := repository.NewPlayerRepository(db)
	venueRepository := repository.NewVenueRepository(db)
	userService := services.NewUserService(userRepository, playerRepository, venueRepository)
	userController := controllers.NewUserController(userService)
	return userController
}

func InitializeVenueController() *controllers.VenueController {
	db := config.GetConnection()
	venueRepository := repository.NewVenueRepository(db)
	venueService := services.NewVenueService(venueRepository)
	venueController := controllers.NewVenueController(venueService)
	return venueController
}
