// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Footpal Support",
            "email": "nathan.mcalinden@unosquare.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bookings": {
            "get": {
                "description": "Retrieve all bookings by user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Booking"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new single or recurring booking",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BookingRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{bookingId}": {
            "get": {
                "description": "Retrieve booking by bookingId",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking ID",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit booking details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking ID",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Cancel active or pending booking",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking ID",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/{bookingId}/matches": {
            "get": {
                "description": "Get all matches linked to booking",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking ID",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Match"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deactivate/{userId}": {
            "delete": {
                "description": "Delete user from Footpal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login to Footpal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/matches": {
            "get": {
                "description": "Retrieve all public matches",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Match"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/matches/{matchId}": {
            "get": {
                "description": "Retrieve match details by matchId",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Match"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Cancel match",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/matches/{matchId}/players": {
            "get": {
                "description": "Retrieve all players opted into a match",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MatchPlayer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/matches/{matchId}/players/{playerId}": {
            "delete": {
                "description": "As a booking/squad admin, remove player from match",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "match"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/players": {
            "get": {
                "description": "Retrieve all players",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Player"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/players/{playerId}": {
            "get": {
                "description": "Get Player information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit player information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PlayerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/players/{playerId}/matches": {
            "get": {
                "description": "Retrieve a players opted in matches",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Match"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/players/{playerId}/matches/{matchId}": {
            "post": {
                "description": "Request to join match",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.JoinMatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Leave match",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/players/{playerId}/matches/{matchId}/pay": {
            "post": {
                "description": "For a match, pay amount owed by player",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MatchPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "For a match, pay amount owed by player",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Payment Type ID",
                        "name": "paymentTypeId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/players/{playerId}/squads": {
            "get": {
                "description": "Retrieve all squads linked to player",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Squad"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/players/{playerId}/squads/{squadId}": {
            "get": {
                "description": "Retrieve squad by squad id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Squad ID",
                        "name": "squadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Player"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Request to join squad",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Squad ID",
                        "name": "squadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/models.JoinMatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register as new player",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/squads": {
            "get": {
                "description": "Retrieve all squads",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Squad"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new squad for building up a team of players",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SquadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controllers.SquadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/squads/{squadId}": {
            "get": {
                "description": "Get squad by squadId",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Squad ID",
                        "name": "squadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Squad"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Squad Info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SquadRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Squad ID",
                        "name": "squadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Squad"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete squad from footpal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Squad ID",
                        "name": "squadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "accepted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/squads/{squadId}/players": {
            "get": {
                "description": "List of players associated with squad",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Squad ID",
                        "name": "squadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SquadPlayerDetails"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/squads/{squadId}/players/{playerId}": {
            "put": {
                "description": "Approve player to join squad",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Squad ID",
                        "name": "squadId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove player from squad",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Squad ID",
                        "name": "squadId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/venues": {
            "get": {
                "description": "Retrieve all venues",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Venue"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit venue details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VenueRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Venue"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new football venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VenueRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/venues/{venueId}": {
            "get": {
                "description": "Retrieve venue by venueId",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Venue"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove venue from Footpal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/venues/{venueId}/admins": {
            "get": {
                "description": "Retrieve venue administrators",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.VenueAdminResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add new administrator to venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VenueAdminRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.VenueAdminResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove administrator from venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/venues/{venueId}/pitches": {
            "get": {
                "description": "Get Pitches by Venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Pitch"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add new pitch to existing venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PitchRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Pitch"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/venues/{venueId}/pitches/{pitchId}": {
            "get": {
                "description": "Get pitch info by venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Pitch"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit pitch details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PitchRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Pitch ID",
                        "name": "pitchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Pitch"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove pitch from venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Pitch ID",
                        "name": "pitchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/venues/{venueId}/pitches/{pitchId}/timeslots": {
            "get": {
                "description": "Retrieve all time slots by Pitch",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Pitch ID",
                        "name": "pitchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/venues/{venueId}/timeslots": {
            "get": {
                "description": "Retrieve all time slots by Venue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "venue"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Venue ID",
                        "name": "venueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "param": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "controllers.SquadResponse": {
            "type": "object"
        },
        "models.Booking": {
            "type": "object",
            "required": [
                "bookingStatusId",
                "created",
                "createdBy",
                "lastUpdated"
            ],
            "properties": {
                "bookingId": {
                    "type": "integer"
                },
                "bookingStatusId": {
                    "type": "integer"
                },
                "created": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "lastUpdated": {
                    "type": "string"
                }
            }
        },
        "models.BookingRequest": {
            "type": "object",
            "required": [
                "day",
                "endTime",
                "matchAccessStatusId",
                "noOfWeeks",
                "pitchId",
                "startTime",
                "venueId"
            ],
            "properties": {
                "day": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 3
                },
                "endTime": {
                    "type": "string"
                },
                "matchAccessStatusId": {
                    "type": "integer"
                },
                "noOfWeeks": {
                    "type": "integer"
                },
                "pitchId": {
                    "type": "integer"
                },
                "squadId": {
                    "type": "integer"
                },
                "startTime": {
                    "type": "string"
                },
                "venueId": {
                    "type": "integer"
                }
            }
        },
        "models.JoinMatchResponse": {
            "type": "object",
            "properties": {
                "matchId": {
                    "type": "integer"
                }
            }
        },
        "models.Login": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5
                }
            }
        },
        "models.Match": {
            "type": "object",
            "required": [
                "bookingId",
                "cost",
                "created",
                "isPaid",
                "lastUpdated",
                "matchAccessStatusId",
                "matchDate",
                "matchStatusId"
            ],
            "properties": {
                "bookingId": {
                    "type": "integer"
                },
                "cost": {
                    "type": "number"
                },
                "created": {
                    "type": "string"
                },
                "isPaid": {
                    "type": "boolean"
                },
                "lastUpdated": {
                    "type": "string"
                },
                "matchAccessStatusId": {
                    "type": "integer"
                },
                "matchDate": {
                    "type": "string"
                },
                "matchId": {
                    "type": "integer"
                },
                "matchStatusId": {
                    "type": "integer"
                }
            }
        },
        "models.MatchPaymentRequest": {
            "type": "object",
            "required": [
                "amountToPay"
            ],
            "properties": {
                "amountToPay": {
                    "type": "number"
                }
            }
        },
        "models.MatchPlayer": {
            "type": "object",
            "required": [
                "amountToPay",
                "matchId",
                "paymentTypeId",
                "playerId"
            ],
            "properties": {
                "amountToPay": {
                    "type": "number"
                },
                "matchId": {
                    "type": "integer"
                },
                "matchPlayerId": {
                    "type": "integer"
                },
                "paymentTypeId": {
                    "type": "integer"
                },
                "playerId": {
                    "type": "integer"
                }
            }
        },
        "models.Pitch": {
            "type": "object",
            "required": [
                "cost",
                "maxPlayers",
                "name",
                "venueId"
            ],
            "properties": {
                "cost": {
                    "type": "number"
                },
                "maxPlayers": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "pitchId": {
                    "type": "integer"
                },
                "venueId": {
                    "type": "integer"
                }
            }
        },
        "models.PitchRequest": {
            "type": "object",
            "required": [
                "cost",
                "maxPlayers",
                "name"
            ],
            "properties": {
                "cost": {
                    "type": "number"
                },
                "maxPlayers": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "models.Player": {
            "type": "object",
            "required": [
                "address",
                "city",
                "nickname",
                "postcode"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 11
                },
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 2
                },
                "playerId": {
                    "type": "integer"
                },
                "postcode": {
                    "type": "string",
                    "maxLength": 8,
                    "minLength": 5
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "models.PlayerRequest": {
            "type": "object",
            "required": [
                "address",
                "city",
                "nickname",
                "postcode"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 11
                },
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 2
                },
                "postcode": {
                    "type": "string",
                    "maxLength": 8,
                    "minLength": 5
                }
            }
        },
        "models.Register": {
            "type": "object",
            "required": [
                "email",
                "forename",
                "surname"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5
                },
                "forename": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "surname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "models.Squad": {
            "type": "object",
            "required": [
                "city",
                "name"
            ],
            "properties": {
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "name": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 2
                },
                "squadId": {
                    "type": "integer"
                }
            }
        },
        "models.SquadPlayerDetails": {
            "type": "object",
            "properties": {
                "forename": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "playerId": {
                    "type": "integer"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "models.SquadRequest": {
            "type": "object",
            "required": [
                "city",
                "name"
            ],
            "properties": {
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "name": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 2
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.Venue": {
            "type": "object",
            "required": [
                "address",
                "city",
                "email",
                "phoneNo",
                "postcode",
                "venueName"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "email": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 10
                },
                "phoneNo": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 11
                },
                "postcode": {
                    "type": "string",
                    "maxLength": 8,
                    "minLength": 5
                },
                "venueId": {
                    "type": "integer"
                },
                "venueName": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "models.VenueAdminRequest": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "integer"
                },
                "venueId": {
                    "type": "integer"
                }
            }
        },
        "models.VenueAdminResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "forename": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "venueAdminId": {
                    "type": "integer"
                }
            }
        },
        "models.VenueRequest": {
            "type": "object",
            "required": [
                "address",
                "city",
                "email",
                "phoneNo",
                "postcode",
                "venueName"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "city": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "email": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 10
                },
                "phoneNo": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 11
                },
                "postcode": {
                    "type": "string",
                    "maxLength": 8,
                    "minLength": 5
                },
                "venueName": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Footpal API",
	Description:      "This is swagger for Footpal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
